let randomNumber = Math.random();
// check if it is less than or equal to 0.01
if (randomNumber <= 0.1) {
    // redirect to a rick roll link
    window.location.href = "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
}
names = ["Getting Wood",
    "Benchmarking",
    "Time to Mine!",
    "Time to Strike!",
    "Time to Chop!",
    "Time to Dig!",
    "Time to Farm!",
    "Mining Milestone",
    "Building Milestone",
    "Farming Milestone",
    "Animal Milestone",
    "Monsters Milestone",
    "Weaponry Milestone",
    "Biomes Milestone",
    "Adventure Milestone",
    "Redstone Milestone",
    "Enchanting Milestone",
    "Statistics Milestone",
    "Nether Milestone",
    "Potions Milestone",
    "End Milestone",
    "Super Challenges Milestone",
    "Advancement Legend",
    "Stone Age",
    "Aww it broke!",
    "Spelunker",
    "Heart of Darkness",
    "My work here is done",
    "Nananananananana...",
    "Filthy Lich",
    "That's the point!",
    "Particle Fan",
    "Deep Slate Nine",
    "Tuff Stuff",
    "Rock Bottom",
    "Moss Maker",
    "Iggy",
    "Lush Hour",
    "Dungeons and Spawners",
    "This is Mine Now!",
    "Eeuuwww!",
    "Steals on Wheels",
    "A Shiny Treat",
    "Gold Mine!",
    "Getting an Upgrade",
    "MOAR Tools",
    "Chestful of Cobblestone",
    "Bulldozer",
    "Meet the Flintstones",
    "Flint Miner",
    "Strike a Light",
    "Bonfire Night",
    "Fossil Fuel",
    "Coal Miner",
    "Master Coal Miner",
    "Hot Topic",
    "Renewable Energy",
    "Smokin' Hot",
    "Coppers and Robbers",
    "Budget Channeling",
    "Surge Protector",
    "Called Shot",
    "Don't Come a Copper!",
    "Wax On",
    "Wax Off",
    "The Statue of Liberty",
    "Sly Copper: The Copper Heist",
    "Copper Miner",
    "Master Copper Miner",
    "Acquire Hardware",
    "Not Chicken McNuggets?",
    "Isn't It Iron Pick",
    "Suit Up",
    "Iron Man",
    "Iron Miner",
    "Master Iron Miner",
    "Gold Rush",
    "Living Like Kings",
    "The Mistake!",
    "Gold Miner",
    "Master Gold Miner",
    "Bling Bling Gone",
    "We've broken our last shovel",
    "MOAR Broken Tools",
    "Where are all your clothes?",
    "DIAM- oh wait no",
    "Lapis Lazuli Miner",
    "Seeing Red",
    "The way to spawn",
    "What's the time, Mr Wolf?",
    "Redstone Miner",
    "G.I. Geode",
    "Good For Your Bones",
    "Galileo Figaro",
    "Pixel Perfect",
    "Blackout",
    "Amethyst Miner",
    "Diamonds!",
    "Iconic Merchandising Prop",
    "Stabcraft",
    "Even MOAR tools",
    "Rest in Pickaxes",
    "Cover Me With Diamonds",
    "Diamond Clad",
    "Diamond Miner",
    "Diamonds to you!",
    "Mineral Collection",
    "Master Diamond Miner",
    "Mr. Bean",
    "Emerald Miner",
    "Oresome!",
    "Hot Stuff",
    "Ice Bucket Challenge",
    "Enchanter",
    "We Need to Go Deeper",
    "Obsidian Miner",
    "Your Door Was Locked",
    "Cut In Half",
    "Stairs? NOOOOO!",
    "Slabs For Days",
    "Ah, My Old Enemy...",
    "Sweet Dreams",
    "Change of Sheets",
    "Rainbow Dreams",
    "Insomniac",
    "Ladder Climbers Inc.",
    "It's a Trap!",
    "Aaaaaand... OPEN!",
    "En Garde",
    "The Walls",
    "Crazy Walls",
    "Stationary Storage",
    "It's a Sign",
    "Colors of the Wind",
    "Barrel Rider",
    "Writer's Block",
    "A Masterpiece!",
    "Mannequin",
    "Armor Display",
    "Art Gallery",
    "Help! I've been framed!",
    "Raise the flag!",
    "No Banner, only Color!",
    "Prepare to Meet Your Loom!",
    "Fruit of the Looms",
    "Torched!",
    "Camping Out",
    "Delicious, Hot Schmoes!",
    "Spawn Camping",
    "Halloween!",
    "One Pickle, Two Pickle, Sea Pickle, Four",
    "Setting up the mood",
    "The Ritual Begins",
    "Happy Birthday!",
    "Festival of Lights",
    "Glowing!",
    "Electric!",
    "Shroom Lightyear",
    "Cerulean!",
    "Expensive!",
    "Fluorescent!",
    "Let There Be Light!",
    "Barking mad",
    "Lost its bark",
    "Professor Oak",
    "Spruce Lee",
    "Professor Birch",
    "The Jungler",
    "The Acacia King",
    "Professor Dark Oak",
    "Yay! I got my wood!",
    "Stripper",
    "Master Logger",
    "I don't like sand",
    "Pathways",
    "Grass Type",
    "Skyblock",
    "Classy Glassy",
    "What a pane",
    "Translucence",
    "Pane in the Glass",
    "Rainbow Sand",
    "Concrete Evidence",
    "The Rainbow You Always Wanted",
    "Clay-Dough!",
    "Bricks!",
    "Pot Planter",
    "Harry Potter",
    "The Terracotta Army",
    "The Glazed Terracotta Army",
    "Rock Collection",
    "Rock Polish",
    "Fake stronghold",
    "Jailhouse Block",
    "Creepers and Withers",
    "Deepslate Conspiracy",
    "Fake fortress",
    "Greek Art Decor",
    "Fake monument",
    "No Chain, No Gain",
    "Blackstonehenge",
    "It's original form",
    "Smooth, dude!",
    "Blast it!",
    "Sharpening Station",
    "Classic Pocket Edition Block",
    "Agent Smithing Table",
    "Bubble, Bubble, Toil and Trouble!",
    "Hot Tub",
    "Washing Machine",
    "Care for the environment",
    "Bapple!",
    "Trimming the treetops",
    "Foilage",
    "Yay! Deadbush!",
    "Ultra Hardcore",
    "Ecologist",
    "An Apple a Day",
    "Berry Nice!",
    "Disen Berry Berry Bad!",
    "Shrooms",
    "Mushroom, mushroom!",
    "Mega Mushroom",
    "Suspicious Looking Stew",
    "I'm gonna be sick!",
    "Sugar, Sugar",
    "It's full of ink",
    "Write your thoughts",
    "An amazing story!",
    "Kelp me!",
    "Aquatic Biofuel",
    "Undersea Gardener",
    "Castaway",
    "It's a cactus!",
    "Spikey!",
    "A Seedy Place",
    "Souperman",
    "Bake Bread",
    "The Lie",
    "Hay there!",
    "Must be your birthday",
    "It's where Nutella comes from",
    "Me Love Cookie",
    "Naturally Carved",
    "The Pie",
    "Olaf",
    "Unmasked",
    "Pumpa Kungen",
    "The melon! The melon! The melon!",
    "Scientific Inaccuracy",
    "The Meloncholy Dane",
    "Die, Potato!",
    "Not today!",
    "24 Carrot Gold",
    "The garbage will do!",
    "Natural Fertiliser",
    "One-course meal",
    "Combine Harvester",
    "What's new with composting?",
    "Come to the countryside!",
    "Serious Dedication",
    "Full Stomach",
    "Vegetarian",
    "Meat Lovers",
    "A Balanced Diet",
    "A Gluttonous Diet",
    "Bacon!",
    "Pork Chop",
    "When Pigs Used to Fly",
    "Pig Slaughterer",
    "Swine Sailing",
    "Rabbit Season",
    "They're breeding like rabbits!",
    "Lucky Charm",
    "Humble Bundle",
    "Getting Into a Stew",
    "In a hole there lived a Rabbit...",
    "Bunny Lover",
    "Fractal",
    "Going Down the Rabbit Hole",
    "Just Keeps Going",
    "Cow Tipper",
    "High Steaks",
    "Repopulation",
    "Milk does your body good",
    "True Cow Tipper",
    "Mooshroom Kingdom",
    "Super Mooshroom",
    "Milkshroom",
    "Mushroom Scientist",
    "Overpopulation",
    "Cool Kids",
    "Fashion Statement",
    "Shoe Shed",
    "Tickle Time!",
    "So Good",
    "Which came first?",
    "Feeding the Ducks Chickens",
    "Chicken Cooper",
    "Chatterbox",
    "Is it a Bird?",
    "Birdkeeper",
    "Wooly!",
    "Feeling Sheepish",
    "Mary Had a Little Lamb...",
    "Have a Shearful Day",
    "Sheariously?",
    "Live and Let Dye",
    "Rainbow Collection",
    "Fuzzy Feet",
    "Goat out of here!",
    "Billy the Kid",
    "Goat Simulator",
    "Whatever Floats Your Goat!",
    "Screaming Milk",
    "Ya like jazz?",
    "Bee Our Guest",
    "Hive Mind",
    "NOT THE BEES!",
    "Total Beelocation",
    "Honey, I'm Home!",
    "Nest, Quick!",
    "Winnie the Pooh",
    "Sticky Situation",
    "WHERE'S THE HONEY LEBOWSKI",
    "Cowboy",
    "Horse Armorer",
    "Colorful Cavalry",
    "Foal Play",
    "So Hungry I Could Eat a Horse!",
    "A Horse in Shining Armor",
    "Are we there yet?",
    "Artificial Selection",
    "Master Farrier",
    "Stay Calmer",
    "So I got that going for me",
    "Llama Llama Duck King",
    "Llama Festival",
    "Heavy Duty Caravan",
    "Blistering Barnacles!",
    "Lead the Way!",
    "Beeloons!",
    "You Lead, I'll Follow",
    "Follow the Leader",
    "Leader of the Pack",
    "Puppies! Yipe!",
    "What Does The Fox Say?",
    "Snow Fox 64",
    "Foxy Thievery",
    "Fishy Business",
    "Direct Fishing",
    "Grinding Nemo",
    "Cephalight",
    "Glow and Behold",
    "Flashy Items",
    "Iceologer Should've Won",
    "Tactical Fishing",
    "Aquarium",
    "Tropical Collection",
    "The Cutest Predator",
    "The Healing Power of Friendship",
    "Thanks a lotl",
    "Axolittle",
    "Axolotl of them",
    "Axeolotl",
    "Delicious Fish",
    "Sushi",
    "Salmonella Poisoning",
    "Catching Nemo",
    "What a piece of junk!",
    "Treasure Hunter",
    "Someone's been here before...",
    "Master Angler",
    "Totally not an AFK fisher!",
    "Poacher",
    "Hey, look, Mom!",
    "Scuttler",
    "Turtle Soldier",
    "Save the Turtles!",
    "Turtle Army",
    "Monster Hunter",
    "Dead Don't Die",
    "There has to be another way...",
    "Iron Belly",
    "Desert Nomad",
    "Zombie Slayer",
    "Dead Really Don't Die",
    "Freezing",
    "Still Talking",
    "Family Reunion",
    "Custom Boss Fight!",
    "Trick or Treat!",
    "Handsome Jack",
    "A Watery Grave",
    "Tridented Shield",
    "Because I'm Aquaman!",
    "Mollusc Man",
    "Captain Etho",
    "Ooh, Baby!",
    "Baby, baby, baby nooo!",
    "Poultry Boy",
    "Spooky Skeleton",
    "Boned",
    "Not Today, Thank You",
    "Frosty",
    "Skeleton Smiter",
    "Paleontologist",
    "The Undead Cavalry",
    "Melting",
    "Spooky Skulls",
    "Bone-to-party",
    "Ew Ew Ew",
    "Poisonous Ew",
    "Spider Smasher",
    "Spider-skeleton",
    "The Ghastly Eyes",
    "Pupil Poppers",
    "What a creep!",
    "Keep your distance",
    "Blast Shield",
    "Controlled Detonation",
    "Aww man",
    "Creeper Killer",
    "Creepy Heads!",
    "Camouflage",
    "The ender of ender",
    "Ender Worm",
    "Tele-morph",
    "Enderman Destroyer",
    "Plane Walker",
    "Impossible...",
    "Basketblock Championship",
    "Witch!",
    "Miracle Drink",
    "Taste of your own medicine",
    "Gelatinous Cube",
    "Trampoline",
    "Slime Squisher",
    "Iskallium Collector",
    "Termite Control",
    "The Phantom Menace",
    "Ricochet Swoop",
    "Phantom Slayer",
    "Anti-Air",
    "Two Birds, One Arrow",
    "We'll handle this",
    "Night Runner",
    "Hell Hunter",
    "Void Ender",
    "Dungeon Crawler",
    "Monsters Hunted",
    "Take Aim",
    "That is so fletch!",
    "Point Blank",
    "Bow Spammer",
    "Sniper Duel",
    "The Mighty Hunter",
    "X-Bow",
    "Ol' Betsy",
    "Who's the Pillager Now?",
    "Artillery",
    "Fireworks Display",
    "Pyrotechnic",
    "Explosive Fire",
    "My Eyes!",
    "Who ya gonna call?",
    "Sir Knight",
    "Shield Luck",
    "Flying Colors",
    "Master Shieldsman",
    "Viking",
    "Axeman",
    "Shovel Knight",
    "Multiclassed",
    "A Throwaway Joke",
    "King of the Sea",
    "The Aquatic Hunter",
    "Poseidon vs Hades",
    "Bombs Away!",
    "Revenge!",
    "Demolitions Expert",
    "Pig Fishing Tournament",
    "Indiana Jones",
    "When Pigs Finally Fly",
    "Snowball Fight",
    "A snowball's chance in hell",
    "Backfire",
    "Egging, Dude!",
    "There's yolk on my head",
    "Expelliarmus!",
    "Slapfish",
    "Diemonds!",
    "Inspector Gadget",
    "Rock, Paper, Shears!",
    "It's time consuming",
    "Loser!",
    "Half Heart Life",
    "For you, my sweet",
    "There's a zombie on the lawn!",
    "Enchanted Forest",
    "Flower Power",
    "The Mighty Jungle",
    "Tarzan",
    "Lion Hunter",
    "Simba",
    "Bamboom!",
    "Construction Worker",
    "Top of the World",
    "Zoologist",
    "Kung Fu Panda!",
    "Edge of the Jungle",
    "Qinling",
    "Pandamonium",
    "Smooth Operator",
    "This Snow is Snowier",
    "Light as a Rabbit",
    "Powder-full",
    "Thin Ice!",
    "Spike Ice!",
    "Thick Ice!",
    "Everybody Loves Ice!",
    "Barbearian",
    "Just Keep Swimming",
    "The sea calls you...",
    "Boaty McBoatface",
    "Dolphin Dasher",
    "So Long & Thanks For The Fish",
    "Free Diver",
    "Sleep with the Fishes",
    "The Great Blocky Reef",
    "In a Pickle",
    "Just a sample",
    "No Reefing!",
    "Echolocation",
    "Pushed Around",
    "Atlantis",
    "Get Ship-rekt!",
    "Boatception",
    "Titanic",
    "X Marks the Spot",
    "Moskstraumen",
    "Kilometre Walk",
    "Ten Thousand Blocks",
    "Voyage",
    "One with the forest",
    "Cold Feet",
    "Warm Feet",
    "Snow Feet",
    "Overgrown!",
    "Wet Feet",
    "Adventuring Time",
    "I hereby dub thee...",
    "I just want to make toast!",
    "What's Up, Doc?",
    "Nyan Sheep",
    "Slenderman",
    "The one and true Johnny",
    "Beethoven",
    "Music To My Ears",
    "Disc Jockey",
    "Overpowered",
    "Now You're Thinking With Portals",
    "Grave Robber",
    "Tomb Raider",
    "Witchcraft",
    "Secret of the Igloo",
    "Raidin' Master",
    "Out of Posts",
    "Riot Shield",
    "I've got a bad feeling about this",
    "Redemption Arc",
    "We're being attacked!",
    "It's so beast-like!",
    "I am Ravager, hear me ROAR!",
    "Picador",
    "Feeling Ill",
    "Hero of the Village",
    "Superhero of the Village",
    "Justice",
    "Buy Low, Sell High",
    "War Is Coming",
    "Veteran of the Village",
    "Travelling Merchant",
    "Shady Deals",
    "Florist",
    "This Dirt is Dirtier",
    "Leaflet Drop",
    "Rebuilding the Oceans",
    "Deal's off!",
    "Do You Want to Trade?",
    "Oh look, it dings!",
    "Prime Specimen",
    "What a Deal!",
    "Crazy Cat Lady",
    "If only cats grew into kittens",
    "A Complete Catalogue",
    "Hired Help",
    "Your Daily FIx",
    "MURDERER!",
    "Rekt!",
    "You are the Pillager",
    "All chained up",
    "Retro Future Knight",
    "Filthy Rich",
    "Filthy Stinkin' Rich",
    "Hey! You two should kiss!",
    "Traveller",
    "Village Settler",
    "Town Planner",
    "Workaholic",
    "Professional",
    "Businessman",
    "The Tribal Villagers",
    "Lilypad Hatter",
    "Council of Crafters",
    "Master Trader",
    "Knowledge is Power",
    "Rare Candy Shop",
    "Mapmaker",
    "Mapmaker's Table",
    "I'm not lost anymore!",
    "Treasure Map",
    "Monumental",
    "Laser Sharks",
    "Spear Fishing",
    "Guardian Destroyer",
    "The Deep End",
    "Dry Spell",
    "Sponge Miner",
    "House of Psychos",
    "Heeere's Johnny",
    "The Shielding",
    "Ghostbuster",
    "Wololo",
    "Postmortal",
    "Under Pressure",
    "Pressure Detector",
    "Metal Plate",
    "Bling Plate",
    "Space Hopper",
    "Space Dropper",
    "Dispense With This",
    "Target Acquired",
    "Target Practise",
    "Bullseye",
    "Tripping Over",
    "Troll Chest",
    "Mozart",
    "Take Notes",
    "Noteworthy",
    "Travelling Bard",
    "Powerful Light",
    "Repeating Repeater",
    "Quirky Quartz",
    "Quartz Miner",
    "Comparing Comparator",
    "Solar Power",
    "Observer Buddy",
    "Vibe Check",
    "On a Rail",
    "Fuel Engine",
    "Electric Rails",
    "Railwayman",
    "Moving Storage",
    "Moving Moving Storage",
    "Mobile Explosion",
    "Moving Parts",
    "Sticky Parts",
    "Engineer",
    "Master Engineer",
    "Librarian",
    "Magical Stockpile",
    "Bow down to me!",
    "To Infinity And Beyond!",
    "Super Efficient",
    "Fortunate Son",
    "Pick Like Silk",
    "Needle Sharp",
    "Undead Slayer",
    "Bane of one-shotting spiders",
    "Newton's Flaming Laser Sword",
    "A rather pointy fence post",
    "Overkill",
    "Over-Overkill",
    "Shotbow",
    "Machine Bow",
    "Arbalistic",
    "Boomerang",
    "Do A Barrel Roll",
    "Zeus",
    "Very Very Frightening",
    "Like a Cat",
    "Armor for the massess",
    "Knocking your socks off",
    "Scuba Gear",
    "Fiery",
    "Gotta Go Fast!",
    "Complete Enchanter",
    "Master Enchanter",
    "Heavy Metal",
    "Curses!",
    "Handmade Blinding",
    "Let It Go!",
    "This name sounds cooler",
    "I'll be back",
    "God of Thunder",
    "Unbreakable",
    "Master Miner",
    "Master Digger",
    "Master Axeman",
    "Master Farmer",
    "Master Knight",
    "Master Sniper",
    "Master Arbalist",
    "Master Armorer",
    "Master Fisher",
    "Master Tridenteer",
    "Out for a stroll",
    "Who needs cars?",
    "I enjoy long walks and playing Minecraft",
    "Marathon",
    "Your legs must be tired",
    "Did you just run across Earth?",
    "Spring in your step",
    "Boing, Boing",
    "Jumping Jacks",
    "Sneaky Snitch",
    "Black Belt Ninja",
    "Ancient Kung Fu Master",
    "Laps in the pool",
    "Olympic Athlete",
    "Olympic Gold Medallist",
    "Minecart Rider",
    "I Like Trains",
    "Global Railway Network",
    "Pig Training",
    "Snout 500",
    "Lightning McPig",
    "Horse Training",
    "Sheriff Firearm",
    "Scourge of the West",
    "Luxury Cruise",
    "Pirate Captain",
    "Sailor of the Seven Seas",
    "Taking It In Stride",
    "Who Needs Boats?",
    "This Ride Is Lit, Yo!",
    "Take to the Skies",
    "Supersonic",
    "Frequent Flyer",
    "Mob Hunter",
    "Bloodthirsty",
    "Kill or be Killed",
    "The Parrots and the Bats",
    "Cupid",
    "Two By Two",
    "The Haggler",
    "Big Spender",
    "STONKS!",
    "Novice Enchanter",
    "Journeyman Enchanter",
    "Elderly Enchanter",
    "Level Up",
    "Overlevelling",
    "XP Grinder",
    "The First Night",
    "Passing the Time",
    "Happy New Year!",
    "Stem Research",
    "What a Fungi!",
    "I am Root",
    "Don't Blink",
    "Twisted",
    "What about Corruption Planks?",
    "Welcome to Warp Zone!",
    "Hot Tourist Destination",
    "Hell Botanist",
    "Spreading Corruption",
    "The Struggle Nether Ends",
    "Roadhog",
    "When Hoglins Breed",
    "Whole Hog",
    "Giddy Up!",
    "Zork Chops",
    "Oh, Shiny!",
    "Cultural Misunderstandings",
    "Those Were The Days",
    "Brute Force",
    "Et tu, Brute?",
    "War Pigs",
    "Gilty!",
    "Wub wub wub",
    "We Got a Live One!",
    "When Piglins Fly",
    "A Piglin's Best Friend",
    "Hot Reels!",
    "This Boat Has Legs",
    "Bobbleheads",
    "This One's Mine!",
    "Jenga",
    "From Whence It Came!",
    "Ancient Restoration",
    "Who is Cutting Onions?",
    "Anchorman",
    "Not Quite 'Nine' Lives",
    "The Tribal Snouts",
    "High Temperature Fluid Monster",
    "Legend of Hell Chicken Riders",
    "Magma Cube Squisher",
    "Giant Floating Jellyfish",
    "Fire Blast Shield",
    "Is it a Balloon?",
    "Return to Sender",
    "Bring Down The Beast",
    "Ghast Slayer",
    "Uneasy Alliance",
    "Electrifying Alliance",
    "Hell's Bells",
    "Hot Spring",
    "Polar Opposites",
    "Nugget in a Biscuit",
    "Stepping on Legos",
    "Dark Ages",
    "Nether Rock Collection",
    "Quicksand",
    "Burnt Right Into Your Soul",
    "A Soul For A Soul",
    "Seeing Stars",
    "Glows in the Dark",
    "Glowstone Miner",
    "The Descent",
    "Nether Say Die",
    "Holy Scrap!",
    "Diamonds Are Not Forever",
    "MOAR Upgraded Tools",
    "A Knight to Nether Forget",
    "Soul Runnings!",
    "Fool Me Twice",
    "Netherite Miner",
    "Master Netherite Miner",
    "Netherite Mad Lad",
    "Get a Lode Of This!",
    "Country Lode, Take Me Home",
    "Lodes of Applications",
    "I'm in Lava With You",
    "Limbo Walker",
    "Subspace Bubble",
    "Let Me Out!",
    "Inception",
    "A Terrible Fortress",
    "The Hunt Begins",
    "Spooky Scary Skeleton",
    "Withering Heights",
    "Decaying Beauty",
    "Bring Home the Beacon",
    "Beaconator",
    "Instant Mining",
    "Beacon Overlord",
    "Into Fire",
    "The Nether's Shield",
    "Blaze Extinguisher",
    "Time to Fire Back",
    "Basis of Brewing",
    "Local Brewery",
    "Ender's Chest",
    "Eye Spy",
    "The End?",
    "Failed Concoctions",
    "Death By Magic",
    "Performance-Enhancing Drugs",
    "Super Strength",
    "A Weak Brew",
    "Zombie Doctor",
    "Mad Scientist",
    "Medic!",
    "Hyper-healing",
    "Nocturnal",
    "The Invisible Player",
    "True Feather Falling",
    "Tank",
    "You Need a Mint",
    "Noxious Fumes",
    "Gas!",
    "Poison Dart",
    "Furious Ammunition",
    "Stayin' Frosty",
    "Marine Marauder",
    "Hopping Mad",
    "A Furious Cocktail",
    "A much more doable challenge",
    "A Furious Test Subject",
    "Gas Bomb",
    "Dragon Shield",
    "Is it a Plane?",
    "Free the End",
    "The Actual End",
    "The Point of No Return",
    "Event Horizon",
    "Cow Jumped Over The Moon",
    "The Next Generation",
    "The Start of Something",
    "The End... Again",
    "What For?",
    "Ring of the End",
    "The Beginning",
    "Remote Getaway",
    "End Bricks!",
    "Getting Chorus",
    "Extrabiologist",
    "Purpurfect",
    "A Wizard's Breakfast",
    "Void Walker",
    "In Your Face, Neil Armstrong",
    "I'm Coming Back, Murph!",
    "No! Don't let me leave, Murph!",
    "The City at the End of the Game",
    "For Mother, Clarence",
    "Portable Storage",
    "Organizational Wizard",
    "Somewhere Over the Rainbow...",
    "Shouldn't my shield levitate too?",
    "Shulker Breaker",
    "Great View From Up Here",
    "Anti-Gravity Generator",
    "Good Luck Getting This One",
    "Off With His Head!",
    "Dragon vs Dragon",
    "Sky's the Limit",
    "Some Breakthrough",
    "Rocketman",
    "Sky High",
    "Uh, Houston? We have a problem",
    "All the Blocks!",
    "All the Items!",
    "Stack all the Blocks!",
    "Stack all the Items!",
    "Telescopic",
    "Highway to Hell",
    "Endergeddon",
    "Potion Master",
    "Biological Warfare",
    "Nuclear Fusion",
    "Zombie Apocalypse",
    "Rise of the Skeletons",
    "Creepergeddon",
    "Dragon Army",
    "Constellation",
    "Warlock",
    "Hearts of the Stack",
    "Abyss Lord",
    "We're in the endgame now",
    "Dragon vs Dragon II",
    "Dragon vs Wither: Pre-Sequel",
    "The Perfect Run",
    "I am Loot!",
    "The World Is Ending",
    "Immortal",
    "Death From All",
    "Ad Astra",
    "I'm in Space!",
    "The Devil's Distance",
    "A Million Blocks Away",
    "Explorer of Worlds",
    "Ultimate Enchanter",
    "Stockbroker",
    "Global Vaccination",
    "How Did We Get Here?"]
desc = ["Attack a tree until a block of wood pops out",
    "Construct a crafting bench",
    "Use planks and sticks to make a pickaxe",
    "Use planks and sticks to make a sword",
    "Use planks and sticks to make a axe",
    "Use planks and sticks to make a shovel",
    "Use planks and sticks to make a hoe",
    "Complete every advancement in the Mining tab",
    "Complete every advancement in the Building tab",
    "Complete every advancement in the Farming tab",
    "Complete every advancement in the Animal tab",
    "Complete every advancement in the Monsters tab",
    "Complete every advancement in the Weaponry tab",
    "Complete every advancement in the Biomes tab",
    "Complete every advancement in the Adventure tab",
    "Complete every advancement in the Redstone tab",
    "Complete every advancement in the Enchanting tab",
    "Complete every advancement in the Statistics tab",
    "Complete every advancement in the Nether tab",
    "Complete every advancement in the Potions tab",
    "Complete every advancement in the End tab",
    "Complete every advancement in the Super Challenges tab. Good luck with this one ;)",
    "Complete every single advancement in BlazeandCave's Advancements Pack",
    "Mine stone with your new pickaxe",
    "Break your first tool",
    "Enter a cave",
    "Submerge yourself in complete darkness",
    "Get caught in a cave-in of gravel",
    "Accidentally hit a bat underground",
    "Use shears to obtain Glow Lichen from an underground cave",
    "Obtain some Pointed Dripstone from a Dripstone Cave",
    "Obtain a Spore Blossom",
    "Mine deep enough that the stone darkens",
    "Mine some Tuff in the deep underground",
    "Dig down to the bottom of the world",
    "Use Bone Meal on Moss to spread its wonderful lushness across hard blocks of stone",
    "Obtain an Azalea",
    "Obtain a stack of all lush-related blocks",
    "Open a chest in a dungeon deep underground",
    "Find an abandoned mineshaft that was not dug out by you",
    "Get stuck in a spider web",
    "Loot a minecart chest from an Abandoned Mineshaft",
    "Eat some Glow Berries",
    "Find a mineshaft on the surface in a mesa biome",
    "Construct a better pickaxe",
    "Craft a stone pickaxe, axe, shovel and hoe",
    "Mine 1728 cobblestone, place it in a chest, then stand on it in victory",
    "Destroy a total of 10,000 blocks of stone",
    "Dig up some flint from a patch of gravel",
    "Dig up 64 pieces of flint",
    "Craft Flint and Steel and use it to light the ground on fire",
    "Light every flammable block on fire",
    "Coal! As in dead dinosaurs!",
    "Mine a stack of coal",
    "Mine enough coal to make a stack of coal blocks",
    "Construct a furnace out of eight stone blocks",
    "Smelt wood trunks using charcoal to make more charcoal",
    "Upgrade your furnace to a smoker using some logs",
    "Smelt a Copper Ingot",
    "Craft a Lightning Rod using Copper Ingots",
    "Protect a villager from an undesired shock without starting a fire",
    "Get struck by lightning while standing on a Lightning Rod",
    "Craft some Cut Copper",
    "Use Honeycombs to wax a Copper Block, preventing it from oxidising",
    "Use an axe to scrape wax off of a Copper Block",
    "Obtain a fully oxidized Block of Copper",
    "Collect a stack of every oxidizing stage of Copper Block, Cut Copper, Cut Copper Slabs and Stairs, and the waxed variants of them all",
    "Mine a stack of Raw Copper",
    "Mine enough copper to make a stack of Copper Blocks",
    "Smelt an iron ingot",
    "Craft or find iron nuggets",
    "Upgrade your pickaxe",
    "Protect yourself with a piece of iron armor",
    "Craft a full suit of iron armor",
    "Mine a stack of Raw Iron",
    "Mine enough iron to make a stack of iron blocks",
    "Smelt a gold ingot",
    "Make golden armor",
    "Put Mending on a piece of golden armor and realise what you are doing in life",
    "Mine a stack of Raw Gold",
    "Mine enough gold to make a stack of gold blocks",
    "Completely use up a golden pickaxe and then seriously reevaluate your life choices",
    "Break all six types of shovels",
    "Break every single tool in the game",
    "Break every type of armor piece in the game",
    "It's still useful for enchanting",
    "Mine enough lapis lazuli to craft a stack of lapis lazuli blocks",
    "Mine some redstone from the deepest caves",
    "Craft a compass in case you forgot where spawn is",
    "Time to clean your clocks! (Or, craft them)",
    "Mine enough redstone to craft a stack of redstone blocks",
    "Find an Amethyst Geode and mine an Amethyst Cluster",
    "Mine some Calcite encasing an Amethyst Geode",
    "Zoom in on something using a Spyglass",
    "Use a Spyglass to stare at a bat from at least 50 blocks away",
    "Craft Tinted Glass using Glass and Amethyst Shards and use it to block out light",
    "Mine a stack of Amethyst Blocks, Amethyst Clusters, and every size of Amethyst Bud",
    "Obtain diamonds",
    "Create a pickaxe of the highest calibre",
    "Do you like my sword sword?",
    "Craft a full diamond tools set",
    "Break your first diamond pickaxe",
    "Diamond armor saves lives",
    "Craft a full suit of diamond armor",
    "Mine a stack of diamonds. Good luck!",
    "Throw diamonds at another player or mob",
    "Craft every type of mineral block",
    "Mine enough diamond to make a stack of diamond blocks",
    "Craft a stack of Raw Iron, Copper and Gold Blocks",
    "Mine a stack of raw emerald ore",
    "Mine a stack of every ore block",
    "Fill a bucket with lava",
    "Form and mine a block of obsidian",
    "Craft an enchanting table",
    "Build, light and enter a Nether Portal",
    "Mine a stack of obsidian. (This might take a while...)",
    "Craft a door to stop monsters from entering your house",
    "Craft some slabs",
    "Craft some stairs",
    "Craft every type of slab",
    "Craft every type of stair",
    "Sleep in a bed to change your respawn point",
    "Dye your bed a different color",
    "Craft every color of bed",
    "Go 30 days without sleep",
    "Climb the ladder!",
    "Craft and place down a trapdoor",
    "Craft and place an iron door",
    "Erect some fencing",
    "Put up some cobblestone walls",
    "Craft every type of wall",
    "Craft and place a chest for storing your items",
    "Craft and place a sign",
    "Dye a sign with each color of dye",
    "Craft and place a barrel. Totally not for riding in",
    "Craft a lectern using wooden slabs and a bookshelf then place it",
    "Put up a painting",
    "Craft and place an armor stand",
    "Place all six sets of armor on six different armor stands",
    "Place every type of painting",
    "Craft an item frame for displaying your items",
    "Craft and place a banner",
    "Craft all 16 banner colors",
    "Craft a loom with string and planks for creating your own banners",
    "Craft all the special banner patterns",
    "Light up the area with some torches",
    "Craft and place a campfire using some logs, sticks and coal",
    "Place every type of cookable food on a campfire",
    "Travel close to 0,0 coordinates and place down a campfire",
    "Light up with jack o' lanterns!",
    "Place four sea pickles in a group underwater",
    "Place a candle and light it using Flint and Steel",
    "Get one stack of Black Candles",
    "Place a candle on a cake",
    "Light up the area using a lantern",
    "Light up the area with glowstone",
    "Light up the area with some redstone lamps",
    "Light up the area with Shroomlight!",
    "Light up the area with soul fire torches and soul fire lanterns!",
    "Light up the area with some sea lanterns",
    "Light up the area with some end rods",
    "Hold a stack of every light-emitting block and item",
    "Craft a bark block",
    "Strip a bark block of its bark",
    "Craft every type of item made out of oak wood",
    "Craft every type of item made out of spruce wood",
    "Craft every type of item made out of birch wood",
    "Craft every type of item made out of jungle wood",
    "Craft every type of item made out of acacia wood",
    "Craft every type of item made out of dark oak wood",
    "Collect all six types of wood",
    "Strip bark from all six types of logs",
    "Cut down a full stack of logs of all types",
    "It's coarse, and rough, and irritating, and it gets everywhere",
    "Use a shovel to create dirt paths",
    "Obtain every type of grass block in your inventory",
    "Place a Grass Block high in the sky",
    "Smelt sand in a furnace to get glass",
    "Craft some glass panes",
    "Craft every color of stained glass",
    "Craft a stack of all 16 colors of stained glass panes",
    "Craft concrete powder using sand, gravel and dye",
    "Create concrete from concrete powder by dropping it into water",
    "Craft every color of concrete",
    "Dig up some clay from a lake",
    "Fire up that clay!",
    "Craft and place a flower pot",
    "Place every type of plant in a flower pot",
    "Craft every color of terracotta (stained clay)",
    "Craft every color of glazed terracotta",
    "Collect all the different types of rocks",
    "Craft every type of polished block",
    "Craft or obtain all forms of normal, cracked, mossy and chiseled stone bricks",
    "Craft or find some iron bars",
    "Engrave sandstone with creeper and wither patterns",
    "Craft all forms of Deepslate, Polished Deepslate, Deepslate Bricks and Deepslate Tiles",
    "Craft or collect all forms of nether brick and red nether brick",
    "Craft all forms of quartz blocks",
    "Craft or collect all forms of prismarine blocks",
    "Craft a chain using an iron ingot and iron nuggets",
    "Craft all forms of Blackstone, Polished Blackstone and Polished Blackstone Bricks",
    "Use your furnace to smelt cobblestone back into normal stone",
    "Smelt normal stone further into smooth stone",
    "Upgrade your furnace to a blast furnace using iron and smooth stone for smelting ores quicker",
    "Craft a grindstone using a stone slab, planks and sticks for repairing tools",
    "Craft a stonecutter using stone and an iron ingot",
    "Craft a smithing table",
    "Fill a cauldron using a bucket",
    "Sit in a cauldron filled with lava",
    "Use a cauldron to clean leather armor, a banner and a shulker box",
    "Plant a sapling",
    "Crunch into an apple",
    "Use shears to obtain a leaf block",
    "Use shears to pick up tall grass or ferns",
    "Get a deadbush cause you're a noob",
    "Craft and eat a normal golden apple",
    "Plant down all six types of saplings",
    "Eat an Apple every day for 30 in-game days",
    "Pick and eat some Sweet Berries",
    "Get stuck in a Sweet Berry Bush. Oh, icky yucky goo!",
    "Gather both types of mushroom",
    "Slurp some mushroom stew",
    "Grow a giant mushroom and then harvest it with silk touch",
    "Slurp some suspicious stew and pray you don't suddenly see giant flying eyeballs in the sky",
    "Slurp every type of suspicious stew",
    "Harvest some sugar cane from a river or an ocean",
    "Obtain some ink from hunting a squid",
    "Use a book, ink and a feather to craft a book and quill",
    "Finish writing in your book or get a book from another player",
    "Collect some kelp from an ocean",
    "Craft a dried kelp block for use as a great fuel source",
    "Craft a full stack of dried kelp blocks",
    "Eat nothing but dried kelp for three in-game days",
    "Break down a cactus in a desert",
    "Run into a cactus",
    "Plant a seed and watch it grow",
    "Beetroot soup gives you souperpowers!",
    "Grow wheat and use it to bake bread",
    "Wheat, sugar, milk and eggs!",
    "Craft a full stack of hay blocks",
    "Eat 100 slices of cake",
    "Obtain some cocoa beans from a jungle",
    "Bake some cookies... and then scoff them all yourself",
    "Harvest some spooky pumpkins",
    "Bake a pumpkin pie",
    "Do you want to build a snow golem?",
    "Shear the Pumpkin off of a Snow Golem to unveil their true face",
    "Carve a full stack of pumpkins",
    "Eat a melon. Be careful not to drop it over a cliff",
    "Craft 9 melon slices back into one block that, when broken, will probably not give you all 9 slices back",
    "Craft a full stack of melon blocks",
    "Squash and eat a potato",
    "Eat a poisonous potato",
    "Eat a golden carrot",
    "Craft a composter using wooden slabs then place it",
    "Fill up a composter",
    "Use bone meal to grow a sapling into a tree",
    "Use bone meal on everything that can be grown",
    "Compost every type of compostable item in a Composter",
    "Plant every single type of crop on farmland",
    "Completely use up a diamond hoe, and then reevaluate your life choices",
    "Fill both your hunger bar and saturation level",
    "Eat every type of fruit, vegetables, and any sort of plant matter",
    "Eat every type of meat, even if uncooked or rotten",
    "Eat everything that is edible, even if it's not good for you",
    "Obtain a full stack of all the foods",
    "Gotta kill this pig pig pig pig!",
    "You know kung fu, how about pork chop?",
    "Craft a carrot on a stick so you can ride a pig off a cliff.",
    "Collect a stack of raw porkchops",
    "Ride a saddled pig in a boat in a minecart",
    "Killing bunnies is cruel. Period",
    "Breed two bunnies together",
    "Get a rabbit's foot",
    "Craft a Bundle using Rabbit Hide and String",
    "Make and eat some rabbit stew",
    "Collect a stack of raw rabbit and rabbit hide",
    "Breed a baby bunny of every variant",
    "Put a Bundle in a Bundle in a Bundle in a Bundle in a Bundle… 16 layers deep",
    "Bring a rabbit to the bottom of the world, then kill it",
    "Eat Rabbit Stew, then avoid eating for the next 3 in-game days",
    "Harvest some leather",
    "The steaks are high for this advancement!",
    "Breed two cows with wheat",
    "Take a swig swig swig swig",
    "Collect a stack of raw beef and leather",
    "Find mooshrooms on a mushroom island",
    "Breed two stubborn mooshrooms together",
    "Milk a mooshroom with a bowl to get mushroom stew",
    "Strike a mooshroom with lightning and see what happens",
    "Breed every type of animal",
    "Craft a leather jacket",
    "Dye some leather pants with one color",
    "Dye 16 pairs of leather boots each with one of the individual colors",
    "Pluck some feathers from a chicken",
    "Can't beat it, can't beat it",
    "The chicken... or the egg??",
    "Breed chickens by feeding them seeds",
    "Collect a stack of raw chicken and feathers",
    "Tame a Parrot using seeds. WARNING: Do not use a cookie!",
    "Look at a Parrot through a Spyglass",
    "Tame all parrot variants",
    "Obtain wool from a sheep by killing it",
    "You'll get over it",
    "Breed two sheep to get a lamb",
    "Use Shears to obtain wool from a sheep",
    "Collect a stack of white wool",
    "Dye Sheep with all 16 colors of wool",
    "Gather all 16 colors of wool",
    "Craft all 16 colors of carpet",
    "Slaughter a Goat",
    "Breed two Goats together using Wheat",
    "Get killed by a Goat that rammed into you. You have Goat to be kidding me!",
    "Get in a Boat and float with a Goat",
    "Milk a screaming Goat",
    "Breed two bees using flowers",
    "Use a bottle to collect Honey from a Beehive with a campfire beneath it so you don't aggravate the bees",
    "Craft a bee hive using planks and honeycombs then place it",
    "Get stung to death by bees",
    "Move a Bee Nest with 3 bees inside using Silk Touch",
    "Craft a stack of honeycomb blocks for building a home out of",
    "Collect a stack of empty bee nests",
    "Drink some honey",
    "Jump into a honey block to slide down it",
    "Drink 100 bottles of honey",
    "Tame a horse by jumping on it over and over again",
    "Make horse armor out of dead horses (No, joking, any leather will do)",
    "Dye 16 sets of leather horse armor each with one of the individual colors",
    "Breed a horse in an effort to get a better one",
    "Feed a Horse every type of food that it can eat",
    "Find diamond horse armor",
    "Tame a donkey",
    "Breed a horse and a donkey to get a mule",
    "Tame all horse variants",
    "Tame a llama",
    "Breed two llamas with hay",
    "Tame all llama variants",
    "Sit on Llamas with all 16 colors of carpet. Getting off will reset your progress",
    "Tame a llama with a strength of 5",
    "Get spat at by a llama",
    "Craft a lead using string and a slimeball, then attach it to a mob",
    "Attach a lead to a bee",
    "Attach a lead to a llama to form a llama caravan",
    "Attach a lead to every mob that can be leashed",
    "Befriend a wolf",
    "Breed two wolves together to get a puppy!",
    "Breed two red foxes with sweet berries",
    "Breed two snow foxes with sweet berries",
    "Give a fox a Totem of Undying",
    "Catch a fish",
    "Catch a fish by directly skewering it with a sword",
    "Skewer a tropical fish",
    "Kill a Glow Squid",
    "Use a Glow Ink Sac to light up a sign",
    "Put an item up for display in a Glowing Item Frame",
    "Kill 100 Glow Squids",
    "Catch a fish... without a fishing rod!",
    "Catch all four types of fish and set them free in an aquarium",
    "Collect all 22 of the common types of tropical fish",
    "Catch an Axolotl in a Bucket",
    "Team up with an Axolotl and win a fight",
    "Feed an Axolotl within an Ocean Monument and watch it go on a Guardian killing spree",
    "Breed two Axolotls together using Tropical Fish",
    "Catch all variants of Axolotls inside a Bucket",
    "Kill an Axolotl with an axe",
    "Cook and eat a fish!",
    "Eat some raw fish",
    "Eat some raw salmon... and not get poisoned after all",
    "Catch a clownfish",
    "Fish out a junk item",
    "Fish out a piece of treasure",
    "Fish out a ratty old pair of boots",
    "Collect a stack of all four types of fish",
    "Fish out all types of items",
    "Kill a turtle for their shells only to find they don't actually drop their shells when killed",
    "Use sea grass to breed a baby turtle",
    "Get a scute from a baby turtle when it grows up",
    "Craft a full turtle shell",
    "Collect a stack of turtle eggs",
    "Collect a stack of scutes",
    "Kill any hostile monster",
    "Kill a zombie",
    "Kill a zombie villager",
    "Stop starvation using rotten flesh",
    "Kill a husk",
    "Collect a stack of rotten flesh",
    "Give a zombie a Totem... so that you have to kill it twice",
    "Bring a husk to a tundra biome and then kill it",
    "Blow up a zombie with a charged creeper to get a zombie head",
    "Reunite all zombie variants (and their baby forms) in one place",
    "Give a zombie full diamond armor and a diamond sword... then kill it",
    "Defeat a mob wearing a pumpkin",
    "Defeat a mob wearing a jack-o-lantern during Halloween",
    "Defeat a Drowned in the briny depths. Gurgle",
    "Block a trident thrown by a Drowned",
    "Obtain a trident from a Drowned",
    "Defeat a Drowned that is holding a nautilus shell",
    "Defeat a Drowned that is holding a nautilus shell and a trident",
    "Kill a baby zombie",
    "Kill one of each of a baby zombie, zombie villager, husk, drowned and zombie pigman",
    "Slay the elusive Chicken Jockey",
    "Kill a skeleton",
    "Grind up some bones into bone meal",
    "Deflect an arrow with a shield",
    "Kill a stray",
    "Collect a stack of bones",
    "Craft or mine a stack of bone blocks",
    "Ride a Skeleton Horse",
    "Bring a stray to a desert biome and then kill it",
    "Blow up a skeleton with a charged creeper to get a skeleton skull",
    "Reunite all skeleton variants and their three-headed overlord in one place",
    "Kill a spider",
    "Kill a cave spider",
    "Collect a stack of string from spiders or cobwebs",
    "Does whatever a spider can",
    "Kill an invisible spider",
    "Eat 1000 Spider Eyes",
    "Kill a creeper",
    "Kill a Creeper with arrows",
    "Survive a creeper's blast with your shield",
    "Persuade a Creeper to blow up using Flint and Steel",
    "That was a nice life you had. Shame it had to end at this time time time",
    "Collect a stack of gunpowder",
    "Blow up a creeper with a charged creeper to get a creeper head",
    "Kill a mob while wearing the same type of mob head",
    "Kill an enderman",
    "Prevent an Endermite from maturing",
    "Damage a mob by teleporting into it",
    "Collect a stack of ender pearls",
    "Find and kill an enderman in all three dimensions",
    "Kill an Enderman with an arrow",
    "Kill Endermen that are holding every block that they can hold",
    "Kill a witch",
    "Drink milk or honey to cure poison when on half a heart",
    "Kill a witch with a splash potion",
    "Kill a slime",
    "Craft a slime block using slimeballs",
    "Collect a stack of slimeballs",
    "Collect enough slimeballs to craft a stack of slime blocks",
    "Kill a silverfish",
    "Get attacked by Phantoms",
    "Deflect a Phantom's swoop with your shield",
    "Collect a stack of Phantom Membranes",
    "Shoot down a phantom with a bow from 30 blocks away",
    "Kill two Phantoms with a piercing arrow",
    "Lure a Phantom into the Nether and then kill it",
    "Defeat all kinds of Overworld night mobs",
    "Defeat all kinds of Nether mobs",
    "Defeat all kinds of End mobs",
    "Defeat all kinds of mobs from special structures",
    "Kill one of every kind of hostile monster",
    "Shoot something with a bow and arrow",
    "Craft a fletching table",
    "Shoot a mob at point-blank range",
    "Take out a mob by bow-spamming",
    "Kill a skeleton with an arrow from more than 50 metres",
    "Hunt all types of animals with your bow",
    "Craft a crossbow using sticks, spider string, iron and a hook",
    "Shoot a crossbow",
    "Give a Pillager a taste of their own medicine",
    "Have nine loaded crossbows in your hotbar. All set!",
    "Use gunpowder and paper to craft fireworks",
    "Craft a firework of every shape and additional effect",
    "Load your crossbow with a firework",
    "Kill a mob using a firework's explosion",
    "Kill a ghast using a firework's explosion",
    "Use planks and iron to craft a shield",
    "Protect yourself from an enemy's attack using your shield",
    "Apply a banner (with no patterns) to your shield",
    "Deflect an attack from every hostile monster",
    "Attack a mob using an axe",
    "Attack a mob using all six types of axes",
    "Hit a mob using all six types of shovels",
    "Hit a mob with every type of weapon",
    "Throw a trident at something. Note: Throwing away your only weapon is not a good idea",
    "Kill a Drowned using a trident from at least 30 metres",
    "Hunt all types of aquatic creatures using your trident",
    "Hunt all types of nether creatures using your trident",
    "Use gunpowder and sand to craft TNT",
    "Blow up a Creeper with some TNT",
    "Blow up every hostile mob with TNT",
    "Pull a pig using a fishing rod",
    "Pull a monster using a fishing rod",
    "Pull a pig from 25 blocks below you and watch it go",
    "The spirit of Christmas... quickly drowned by a battle",
    "Defeat a Blaze using snowballs",
    "Kill a Blaze using a Blaze Rod while both you and it are on fire",
    "Vandalise something with eggs",
    "Catapult an egg onto a zombie's head",
    "Hit a mob with a stick",
    "Slap a mob across the face with a fish",
    "Hit a mob with diamonds",
    "Kill a zombie while holding a spyglass",
    "Beat a zombie at rock, paper, shears",
    "Kill something using a clock",
    "Die twice within ten seconds",
    "Be on half a heart of health for a minute",
    "Pick a flower for someone special",
    "Find a sunflower plains",
    "Find a flower forest",
    "Collect all types of flowers",
    "Go for a safari in the jungle",
    "Swing (or climb) on some vines",
    "Feed an Ocelot fish to try and gain its trust",
    "Breed a baby ocelot",
    "Break down some bamboo",
    "Craft and use some scaffolding",
    "Place scaffolding to the world limit",
    "Breed two pandas to get a baby panda",
    "Get beaten up by an angry panda",
    "Enter a Modified Jungle Edge - the rarest biome in Minecraft",
    "Breed a rare brown panda",
    "Feed cake to every type of panda",
    "Slip and slide on some ice",
    "Fall into some Powder Snow",
    "Walk on Powder Snow… without sinking in it",
    "Pick up some Powder Snow in a Bucket",
    "Mine some ice using a silk touch pickaxe",
    "Break down an ice spike using a silk touch pickaxe",
    "Craft or mine a blue ice block from an iceberg",
    "Obtain a stack of every type of ice in your inventory",
    "It may be illegal to hunt polar bears in real life, but not in Minecraft",
    "Go for a swim",
    "Find an ocean",
    "Craft and ride a boat to sail on the high seas",
    "Get a speed boost from your friendly underwater companions",
    "Get murdered by dolphins",
    "Stay underwater for 2 minutes",
    "Spend a day underwater",
    "Come across a coral reef in an ocean",
    "Collect some sea pickles from a coral reef",
    "Collect some coral from a coral reef",
    "Collect all colors of coral blocks, coral plants and coral fans (including dead ones)",
    "Feed a dolphin fish to have it lead you to treasure",
    "Enter a bubble column",
    "Explore some Underwater Ruins",
    "Come across a sunken ship",
    "Get in a boat within a shipwreck",
    "Find a shipwreck in an iceberg biome",
    "Use a treasure map to find Buried Treasure",
    "Construct a Conduit in the ocean",
    "It's not that far in real life",
    "A journey that long begins with a simple step",
    "A hundred kilometres!",
    "Discover every forest biome",
    "Discover every cold biome",
    "Discover every dry biome",
    "Discover every snow biome",
    "Discover every overgrown biome",
    "Discover every wet biome",
    "Discover every biome",
    "Obtain a name tag",
    "Name a bunny 'Toast'",
    "Turn a mob upside-down",
    "Nyan Nyan Nyan Nyan...",
    "Defeat this terrifying monster",
    "Defeat Johnny",
    "Craft a jukebox with planks and a diamond",
    "Play a music disc in a jukebox",
    "Listen to all the music discs",
    "Obtain a Notch Apple",
    "Find a broken Nether Portal in the Overworld",
    "Enter a pyramid in a desert",
    "Enter a jungle temple",
    "Find a witch hut in a swamp",
    "Find an igloo in a snowy tundra",
    "Discover every structure type",
    "Enter a Pillager Outpost",
    "Deflect a Pillager's crossbow bolt",
    "Kill a raid captain. Maybe consider staying away from villages for the time being...",
    "Befriend a Pillager that doesn't have a crossbow",
    "Trigger a Pillager Raid",
    "Slay a Ravager in a raid",
    "Have a Ravager slam into your shield",
    "Hit a Ravager with a thrown trident",
    "Defeat every type of Illager as part of a raid",
    "Triumph over a full raid for the first time",
    "Defeat enough raid captains to obtain a stack of Ominous Banners",
    "Kill each type of Illager with a single crossbow arrow",
    "Trade with a villager while under the Hero of the Village effect",
    "Defeat enough Illager Patrol leaders to attain the highest level of Bad Omen",
    "Attain the highest level of Hero of the Village",
    "Trade with a Wandering Trader",
    "Trade with the Wandering Trader while he is invisible",
    "Trade for a flower from the Wandering Trader",
    "Trade for some Rooted Dirt from a Wandering Trader",
    "Fall through a Big Dripleaf",
    "Trade for a coral block from the Wandering Trader",
    "Get spat at by one of the Trader Llamas",
    "Find an NPC village",
    "Ring a bell in a village",
    "Find Tall Grass or a Large Fern inside a village chest",
    "Succesfully trade with a villager",
    "Tame a stray cat in a village",
    "Breed two cats together to get a kitty!",
    "Tame all cat variants!",
    "Summon an Iron Golem to help defend a village",
    "Use an Iron Ingot to repair a damaged Iron Golem",
    "Kill a villager",
    "Get killed by a natural iron golem defending its village",
    "Murder one of every villager profession using a crossbow",
    "Trade for a piece of chain armor from an armorer villager",
    "Trade for a full suit of chain armor from an armorer villager",
    "Make 64 emeralds",
    "Make 64 emerald blocks",
    "Use a Spyglass to look at two Villagers sitting in a Boat from at least 50 blocks away",
    "Travel to every type of village and trade with a villager in each",
    "Trade for a new bell to establish a new village",
    "Craft and place every type of villager workstation",
    "Craft a stack of all the villager job site blocks",
    "Trade with a villager at master level",
    "Trade with every type of villager career",
    "Breed and trade with a jungle villager",
    "Breed and trade with a swamp villager",
    "Trade with a villager at height limit",
    "Trade with every type of villager career at master level",
    "Trade for an enchanted book",
    "Trade for a Bottle o' Enchanting from a Cleric",
    "Craft or trade an empty map",
    "Craft a cartography table with paper and planks",
    "Right-click a banner with a map",
    "Trade for an explorer map",
    "Find an Ocean Monument",
    "Defeat a Guardian",
    "Kill a Guardian with arrows",
    "Collect a stack of prismarine shards and crystals",
    "Defeat an Elder Guardian",
    "Dry a sponge in a furnace",
    "Collect a stack of sponges from ocean monuments",
    "Find a Woodland Mansion",
    "Kill a Vindicator",
    "A shield does no better than a locked door",
    "Bust a Vex summoned by an Evoker",
    "Defeat an Evoker",
    "Use a Totem of Undying to cheat death",
    "Craft a pressure plate",
    "Use a pressure plate to craft a detector rail",
    "Craft an iron weighted pressure plate",
    "Craft a golden weighted pressure plate",
    "Craft a hopper for item transportation",
    "Craft a dropper for item transportation",
    "Construct a dispenser",
    "Put up a Target for archery practise",
    "Hit a Target with all types of projectiles",
    "Hit the bullseye of a Target Block with an arrow",
    "Craft a tripwire hook for your traps",
    "Craft a trapped chest to troll your friends",
    "Craft a note block",
    "Tune a Note Block through every possible note",
    "Play every possible instrument on a Note Block",
    "Play a Note Block in every type of biome",
    "Craft and place a redstone torch",
    "Craft a redstone repeater for delaying signals",
    "Mine Nether Quartz",
    "Mine enough nether quartz to craft a stack of nether quartz blocks",
    "Craft a redstone comparator",
    "Craft a daylight sensor",
    "Craft an observer",
    "Obtain a Sculk Sensor",
    "Craft a minecart",
    "Craft a powered minecart",
    "Making furnace minecarts completely useless",
    "Craft a stack of all the different types of rails",
    "Put a chest in a minecart",
    "Put a hopper in a minecart",
    "Put TNT in a minecart",
    "Craft a piston so you can push things",
    "Craft a sticky piston so you can pull things",
    "Craft all types of redstone components",
    "Craft a stack of all types of redstone components",
    "Build some bookshelves for your enchanting table",
    "Obtain a full stack of bottles of enchanting",
    "Obtain Power V",
    "Obtain Infinity on a bow",
    "Obtain Efficiency V",
    "Obtain Fortune III",
    "Use a Silk Touch enchanted pickaxe to obtain diamond ore as a block",
    "Obtain Sharpness V",
    "Obtain Smite V",
    "Obtain Bane of Arthropods V",
    "Have a diamond sword with Fire Aspect II",
    "Enchant a wooden sword with Sharpness V. Not really the best weapon, but it could be a minor annoyance to someone",
    "Deal eight hearts of damage in a single blow",
    "Deal 16 hearts of damage in a single blow",
    "Shoot three arrows at once with a crossbow",
    "Fire a crossbow as rapidly as possible",
    "Kill five unique mobs with one crossbow shot",
    "Turn your trident into a boomerang by getting Loyalty on it",
    "Get Riptide on a trident so you can shoot yourself through the water",
    "Obtain Channeling on a trident",
    "Strike a Villager with lightning",
    "Obtain boots enchanted with Feather Falling",
    "Obtain all protection related enchantments",
    "Obtain Knockback and Punch enchantments",
    "Obtain every water related enchantment",
    "Obtain every fire related enchantment",
    "Obtain the Soul Speed enchantment from a Bastion or bartering with Piglins",
    "Get every enchantment throughout your enchanting career",
    "Get every enchantment at its max level throughout your enchanting career",
    "Craft an anvil",
    "Obtain both types of curses",
    "Wear a carved pumpkin enchanted with Curse of Binding",
    "Obtain boots enchanted with Frost Walker",
    "Name your Diamond Sword 'Diamond Edge'",
    "Name your Bow 'Terminator'",
    "Name your Trident with Loyalty III and Channeling 'Mjolnir'",
    "Obtain Mending on an item",
    "Create a pickaxe with all possible enchantments at max level",
    "Create a shovel with all possible enchantments at max level",
    "Create a axe with all possible enchantments at max level",
    "Create a hoe with all possible enchantments at max level",
    "Create a sword with all possible enchantments at max level",
    "Create a bow with all possible enchantments at max level",
    "Create a crossbow with all possible enchantments at max level",
    "Create a full suit of armor with all possible enchantments at max level",
    "Create a fishing rod with all possible enchantments at max level",
    "Create a trident with all possible enchantments at max level",
    "Walk 10km",
    "Walk 100km",
    "Walk 1000km",
    "Sprint 42.195km",
    "Sprint 250km",
    "Sprint 1000km",
    "Jump 1000 times",
    "Jump 10,000 times",
    "Jump 100,000 times",
    "Sneak 100m",
    "Sneak 1km",
    "Sneak 10km",
    "Swim 1km",
    "Swim 10km",
    "Swim 100km",
    "Ride 1km in a minecart",
    "Ride 10km in a minecart",
    "Ride 100km in a minecart",
    "Ride 100 m on a pig",
    "Ride 1 km on a pig",
    "Ride 10 km on a pig",
    "Ride 1 km on a horse",
    "Ride 10 km on a horse",
    "Ride 50 km on a horse",
    "Sail 1km in a boat",
    "Sail 10km in a boat",
    "Sail 50km in a boat",
    "Ride 100m on a Strider",
    "Ride 1km on a Strider",
    "Ride 10km on a Strider",
    "Fly 10 km with elytra",
    "Fly 100km with elytra",
    "Fly 1000km with elytra",
    "Defeat 250 mobs",
    "Defeat 2500 mobs",
    "Defeat 25,000 mobs",
    "Breed 100 animals",
    "Breed 500 animals",
    "Breed 2500 animals",
    "Trade with villagers 100 times",
    "Trade with villagers 500 times",
    "Trade with villagers 2500 times",
    "Enchant 10 items",
    "Enchant 50 items",
    "Enchant 250 items",
    "Reach 30 experience levels",
    "Reach 100 experience levels",
    "Reach 300 experience levels",
    "Survive the first night in your brand new world",
    "Play for 100 days",
    "Play for a whole year!",
    "Attack a huge Nether Fungi until a stem pops out",
    "Pick up Crimson or Warped Fungus",
    "Pick up some crimson roots",
    "Climb on some Weeping Vines",
    "Climb on some Twisted Vines",
    "Craft every item made out of crimson wood",
    "Craft every item made out of warped wood",
    "Explore every Nether biome",
    "Gather a stack of every Nether plant",
    "Place one of every Nether block in the Overworld",
    "Place one of every Nether block in The End",
    "Hunt a Hoglin for food",
    "Breed a baby Hoglin using Crimson Fungi",
    "Get mauled by a Hoglin",
    "Punch a baby Hoglin that is being ridden by a baby Piglin",
    "Bring a Hoglin into the Overworld to zombify it, then kill it for zorkchops",
    "Distract Piglins with gold",
    "Slay a Piglin in battle... or an accidental incursion",
    "Fight your way into a Bastion Remnant",
    "Defeat a Piglin Brute in a Bastion Remnant",
    "Get murdered by Piglin Brutes",
    "Loot a chest in a Bastion Remnant",
    "Mine some Gilded Blackstone from a Bastion Remnant",
    "Obtain the Pigstep music disc from a Bastion Remnant",
    "Bring a Piglin into the Overworld then spare it from an eternity of zombification",
    "Give a piglin elytra then kill it",
    "Give a total of 500 gold to Piglins during your nether adventures",
    "Reel in a Strider using a Fishing Rod",
    "Ride a Strider with a Warped Fungus on a Stick",
    "Breed two Striders using Warped Fungus",
    "Kill a Zombified Piglin that is riding a Strider and take its steed",
    "Ride a Strider riding another Strider riding a boat riding a minecart",
    "Find a broken Nether Portal in the Nether",
    "Rebuild and reactivate a Ruined Portal",
    "Obtain Crying Obsidian from a Ruined Portal or bartering with Piglins",
    "Craft a Respawn Anchor using Crying Obsidian and Glowstone then place it down",
    "Charge a Respawn Anchor to the maximum",
    "Kill a zombie pigman",
    "Kill a magma cube",
    "Kill a chicken jockey in the nether",
    "Collect a stack of magma cream",
    "Shoot down a ghast",
    "Block the explosion of a Ghast's fireball",
    "Look at a Ghast through a Spyglass",
    "Destroy a Ghast with its fireball",
    "Bring down a ghast with a sword",
    "Collect a stack of ghast tears",
    "Rescue a Ghast from the Nether, bring it safely back home to the Overworld... and then kill it",
    "Smite a ghast with lightning from the Overworld's heavens",
    "Ring a bell in the Nether",
    "Sit in water in the Nether",
    "Start freezing in the Nether",
    "Mine Nether Gold Ore for a pile of gold nuggets",
    "Walk on some hot Magma Blocks in the Nether",
    "Mine Blackstone from a Basalt Deltas biome",
    "Mine a stack of Netherrack, Basalt, Blackstone and Magma in the Nether",
    "You sink like quicksand, but move slow like mud",
    "Get caught on Soul Fire",
    "Place down a Soul Campfire",
    "Mine some glowstone dust from the Nether",
    "Shoot a mob with a spectral arrow",
    "Mine and craft a stack of glowstone blocks",
    "Dig down into the deepest depths of the Nether",
    "Excavate out some Ancient Debris from deep beneath the lava oceans",
    "Smelt Ancient Debris into Netherite Scrap",
    "Use Gold Ingots and Netherite Scrap to make a Netherite Ingot",
    "Craft a Netherite Pickaxe, Axe, Shovel and Hoe",
    "Upgrade your diamond armor to netherite armor",
    "Step on Soul Sand with Netherite Boots enchanted with Soul Speed III",
    "Completely use up a netherite hoe. Clearly you have chosen... poorly",
    "Mine a stack of Ancient Debris",
    "Mine enough Ancient Debris to make a stack of Netherite Ingots (don't worry, this datapack won't make you mine a stack of Netherite Blocks, I'm not that evil…)",
    "Be an absolute madlad and grind enough Ancient Debris to make a stack of Netherite Blocks (this is hidden and not required for Advancement Legend btw…)",
    "Craft a Lodestone using Chiseled Stone Bricks and a Netherite Ingot",
    "Right click on a Lodestone with a Compass to create a Lodestone Compass",
    "Create a Lodestone Compass in all three dimensions",
    "Hit something while you and it are in lava",
    "Get above the roof in the nether",
    "Use the Nether to travel 7km in the Overworld",
    "Stay in the Nether for twenty ingame days",
    "Build a machine that can break a hole in the roof of the Nether",
    "Break your way into a Nether Fortress",
    "Kill a wither skeleton",
    "Obtain a wither skeleton's skull",
    "Summon the wither",
    "Pick up some Wither Roses from the damage the Wither wrought on your world",
    "Construct and place a beacon",
    "Bring a beacon to full power",
    "Hold a Diamond or Netherite Pickaxe enchanted with Efficiency V while under the Haste II effect",
    "Acquire every beacon-induced effect at once",
    "Relieve a Blaze of its rod",
    "Block some Blaze fireballs",
    "Collect a stack of blaze rods",
    "Craft a stack of fire charges",
    "Harvest some nether wart from a nether fortress",
    "Craft a brewing stand for brewing potions",
    "Craft an ender chest for some extra inventory space",
    "Follow an Ender Eye",
    "Enter the End Portal",
    "Brew a Mundane and Thick Potion",
    "Kill a mob with a splash potion",
    "Brew a Speed Potion for cheating on athletics",
    "Brew a Strength Potion for cheating on weightlifting",
    "Brew up a potion of Weakness",
    "Cure a zombie villager",
    "Cure a zombie villager of every profession",
    "Brew a healing potion",
    "Brew and drink a regeneration potion",
    "Brew and drink a night vision potion",
    "Brew and drink an invisibility potion",
    "Brew and drink a slow falling potion",
    "Become nearly invincible to all damage using a Turtle Master Potion",
    "Collect dragon's breath in a glass bottle",
    "Use dragon's breath to brew up lingering potions",
    "Kill a mob using a lingering potion",
    "Craft tipped arrows of poison",
    "Craft every type of tipped arrow",
    "Swim in lava while having the Fire Resistance effect",
    "Swim in water while having the Water Breathing effect",
    "Get jump boost from a beacon or potion",
    "Have every potion effect applied at the same time",
    "Get all the effects possible during your life (not all at the same time)",
    "Get attacked by a mob with every potion effect",
    "Ignite a Creeper of each possible effect using Flint and Steel",
    "Attempt to block the dragon's attacks",
    "Look at the Ender Dragon through a Spyglass",
    "Good luck",
    "Get killed by an Enderman in the End",
    "Fall into the void",
    "Survive void damage",
    "Bring a cow from the overworld to the End and then kill it",
    "Hold the Dragon Egg",
    "Craft your first ender crystal",
    "Respawn the Ender Dragon",
    "Craft 64 ender crystals",
    "Defeat the Ender Dragon 20 times",
    "Say goodbye to the Wither",
    "Escape the island",
    "Craft end bricks from end stone",
    "Attack a chorus tree until it collapses",
    "Plant a chorus flower in the Overworld for study",
    "Craft or collect purpur blocks, stairs, pillars and slabs",
    "Eat a stack of Chorus Fruit in one go",
    "Explore every End biome",
    "Colonise the End with potato crops",
    "Travel far into the End dimension",
    "Travel so far into the End dimension you might as well be on another planet",
    "Go on in, what could happen?",
    "Kill a shulker",
    "Use shulker shells to craft a shulker box",
    "Name a Shulker Box 'Blocks' for storing your blocks",
    "Craft all 16 shulker box types",
    "Block a Shulker's bullet with your shield",
    "Collect a stack of shulker shells",
    "Levitate up a distance of 50 metres",
    "Bring a Shulker into the Overworld and let it give you anti-gravity",
    "Kill a baby Turtle, a Witch, a Phantom, an Elder Guardian and a Piglin Brute with one piercing arrow in the End",
    "Collect a dragon's head from the bow of an end ship",
    "Kill the Ender Dragon while wearing a Dragon Head",
    "Find an Elytra",
    "Exhaust your elytra",
    "Fill your inventory with full stacks of firework rockets",
    "Climb up to the world height limit",
    "Fly up to a ridiculous height",
    "Obtain all the blocks!",
    "Obtain all the items!",
    "Obtain a stack of all the blocks!",
    "Obtain a stack of all the items!",
    "Look at every mob using a Spyglass, each from at least 25 blocks away",
    "Send every mob to the Nether... and kill them all there",
    "Send every mob to the End... and kill them all there",
    "Kill every mob in the game with splash potions",
    "Kill every mob in the game with lingering potions",
    "Strike every mob that can transform with lightning at once",
    "Obtain a stack of Zombie Heads",
    "Obtain a stack of Skeleton Skulls",
    "Obtain a stack of Creeper Heads",
    "Obtain a stack of Ender Dragon Heads",
    "Collect 64 Nether Stars",
    "Obtain a stack of Beacons",
    "Collect 64 Hearts of the Sea",
    "Obtain a stack of Conduits",
    "Construct a village in the End and defend it from a raid",
    "Defeat the Ender Dragon while wearing a dragon head... without touching the ground",
    "Defeat the Wither while wearing a Dragon head... without touching the ground",
    "Summon the Ender Dragon, the Wither, and a Raid within thirty seconds of each other, then defeat all of them without taking damage",
    "Open up every type of loot chest",
    "Summon ten withers at once",
    "Fill your entire inventory with Totems of Undying",
    "Get killed by every mob that can kill you",
    "Reach an altitude of 10,000 blocks above the world",
    "Levitate up a distance of 256 blocks",
    "Use the Nether to travel 666km in the Overworld",
    "Travel a million blocks away from spawn",
    "Discover every biome including special biomes",
    "Collect every type of enchantment at every level",
    "Trade with every profession from every biome type",
    "Cure a zombie villager of every profession... from every biome",
    "Have every effect applied at the same time"]
speed = 25;
var nameElement = document.getElementById("adv-name");
var descElement = document.getElementById("adv-desc");
var id = Math.floor(Math.random() * names.length);
var s_name = names[id];
var s_desc = desc[id];
i = 0;


setTimeout(typeWriter, 0);
function typeWriter() {
    if (i < 170) {
        i++;
        nameElement.textContent = s_name.substring(0, i);
        descElement.textContent = s_desc.substring(0 - s_name.length, i - s_name.length);
        setTimeout(typeWriter, speed);
    }
}